<?php // path: config/cfg_stableDiffusionConfig.php

const __STABLE_DIFFUSION_API_URL__ = 'https://stablediffusionapi.com/api/v3/text2img';
const __STABLE_DIFFUSION_API_KEY__ = 'Your_STABLE_DIFFUSION_API_Key';
const __STABLE_DIFFUSION_NEGATIVE_PROMPT__ = null;
const __STABLE_DIFFUSION_IMAGE_WIDTH__ = '512';
const __STABLE_DIFFUSION_IMAGE_HEIGHT__ = '512';
const __STABLE_DIFFUSION_SAMPLES__ = '1';
const __STABLE_DIFFUSION_NUM_INFERENCES_STEPS__ = '20';
const __STABLE_DIFFUSION_SEED__ = null;
const __STABLE_DIFFUSION_GUIDANCE_SCALE__ = '7.5';
const __STABLE_DIFFUSION_SAFETY_CHECKER__ = 'yes';
const __STABLE_DIFFUSION_MULTI_LINGUAL__ = 'no';
const __STABLE_DIFFUSION_PANORAMA__ = 'no';
const __STABLE_DIFFUSION_SELF_ATTENTION__ = 'no';
const __STABLE_DIFFUSION_UPSCALE__ = 'no';
const __STABLE_DIFFUSION_EMBEDDINGS_MODEL__ = null;
const __STABLE_DIFFUSION_WEBHOOK__ = null;
const __STABLE_DIFFUSION_TRACK_ID__ = null;